// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectEntra21.src.Infrastructure;

namespace ProjectEntra21.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220803023938_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ProjectEntra21.src.Domain.Entiteis.Cell", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("CodeCell")
                        .HasColumnType("int")
                        .HasColumnName("codigo_celula");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 8, 2, 23, 39, 38, 42, DateTimeKind.Local).AddTicks(7960))
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 8, 2, 23, 39, 38, 42, DateTimeKind.Local).AddTicks(8279))
                        .HasColumnName("ultima_modificao_em");

                    b.Property<int>("StatusCell")
                        .HasColumnType("int")
                        .HasColumnName("status_celula");

                    b.HasKey("Id");

                    b.HasAlternateKey("CodeCell");

                    b.ToTable("Celula");
                });

            modelBuilder.Entity("ProjectEntra21.src.Domain.Entiteis.CellEmployeer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("Code")
                        .HasColumnType("bigint")
                        .HasColumnName("codigo");

                    b.Property<int>("CodeCell")
                        .HasColumnType("int")
                        .HasColumnName("codigo_celula");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 8, 2, 23, 39, 38, 44, DateTimeKind.Local).AddTicks(4563))
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 8, 2, 23, 39, 38, 44, DateTimeKind.Local).AddTicks(5013))
                        .HasColumnName("ultima_modificao_em");

                    b.Property<long>("RegisterEmployeer")
                        .HasColumnType("bigint")
                        .HasColumnName("matricula_funcionario");

                    b.HasKey("Id");

                    b.HasAlternateKey("Code", "RegisterEmployeer");

                    b.ToTable("CelulaFuncionario");
                });

            modelBuilder.Entity("ProjectEntra21.src.Domain.Entiteis.Employeer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 8, 2, 23, 39, 38, 32, DateTimeKind.Local).AddTicks(8755))
                        .HasColumnName("criado_em");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("documento");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 8, 2, 23, 39, 38, 36, DateTimeKind.Local).AddTicks(6910))
                        .HasColumnName("ultima_modificao_em");

                    b.Property<int>("LevelEmployeer")
                        .HasColumnType("int")
                        .HasColumnName("nivel_funcionario");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("funcao");

                    b.Property<long>("Register")
                        .HasColumnType("bigint")
                        .HasColumnName("matricula");

                    b.HasKey("Id");

                    b.HasAlternateKey("Register");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("ProjectEntra21.src.Domain.Entiteis.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("AmountEnter")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_entrada");

                    b.Property<int>("AmountFinished")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_saida");

                    b.Property<long?>("CellId")
                        .HasColumnType("bigint");

                    b.Property<long>("Code")
                        .HasColumnType("bigint")
                        .HasColumnName("codigo_ordem");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 8, 2, 23, 39, 38, 48, DateTimeKind.Local).AddTicks(2942))
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 8, 2, 23, 39, 38, 49, DateTimeKind.Local).AddTicks(1706))
                        .HasColumnName("data_ordem");

                    b.Property<long?>("EmployeerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 8, 2, 23, 39, 38, 48, DateTimeKind.Local).AddTicks(3512))
                        .HasColumnName("ultima_modificao_em");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Code");

                    b.HasIndex("CellId");

                    b.HasIndex("EmployeerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Ordem");
                });

            modelBuilder.Entity("ProjectEntra21.src.Domain.Entiteis.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("Code")
                        .HasColumnType("bigint")
                        .HasColumnName("codigo_produto");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 8, 2, 23, 39, 38, 45, DateTimeKind.Local).AddTicks(9352))
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 8, 2, 23, 39, 38, 45, DateTimeKind.Local).AddTicks(9800))
                        .HasColumnName("ultima_modificao_em");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_produto");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("tipo_produto");

                    b.HasKey("Id");

                    b.HasAlternateKey("Code");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("ProjectEntra21.src.Domain.Entiteis.Order", b =>
                {
                    b.HasOne("ProjectEntra21.src.Domain.Entiteis.Cell", "Cell")
                        .WithMany()
                        .HasForeignKey("CellId");

                    b.HasOne("ProjectEntra21.src.Domain.Entiteis.Employeer", "Employeer")
                        .WithMany()
                        .HasForeignKey("EmployeerId");

                    b.HasOne("ProjectEntra21.src.Domain.Entiteis.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Cell");

                    b.Navigation("Employeer");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
